channel: stable-4.10
version: 4.10.47
subscriptions:
  - name: kiali-ossm
    namespace: openshift-operators
    channel: stable
  - name: servicemeshoperator
    namespace: openshift-operators
    channel: stable
  - name: amq-streams
    namespace: openshift-operators
    channel: stable