apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: quay.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
#{{- if $.Values.persistence.enabled -}}
        volumeMounts:
        - mountPath: /tmp/app
          name: app-volume
#{{- end }}
{{- if $.Values.persistence.enabled -}}
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: {{ .Values.app.name }}-claim
{{- end }}