apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: {{ .Values.channel }}
  clusterID: {{ .Values.id }}
  desiredUpdate:
    version: {{ .Values.version }}
    force: true