#apiVersion: config.openshift.io/v1
#kind: ClusterVersion
#metadata:
#  name: version
#spec:
#  channel: {{ .Values.channel }}
#  clusterID: {{ .Values.id }}
#  desiredUpdate:
#    version: {{ .Values.version }}
#    force: true
#---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-cluster-version
  namespace: openshift-gitops
spec:
  patches:
    - id: patch1
      patchTemplate: |
        spec:
          channel: {{ .Values.channel }}
          desiredUpdate:
            version: {{ .Values.version }}
            force: true
      patchType: application/strategic-merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          name: openshift-gitops
          kind: Namespace
        - apiVersion: v1
          name: openshift-gitops-argocd-application-controller
          namespace: openshift-gitops
          kind: ServiceAccount
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        name: version
        kind: ClusterVersion
  serviceAccountRef:
    name: openshift-gitops-argocd-application-controller