apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-cluster-version
  namespace: resource-locker-operator
spec:
  patches:
    - id: patch1
      patchTemplate: |
        spec:
          channel: {{ .Values.channel }}
          desiredUpdate:
            version: {{ .Values.version }}
            force: true
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        name: version
        kind: ClusterVersion