{{- range .Values.subscriptions }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  channel: {{ .channel }}
  installPlanApproval: Automatic
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: openshift-marketplace
---
{{- if ne .namespace "openshift-operators" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  generatedName: {{ .name }}-
  namespace: {{ .namespace }}
spec: {}
---
{{- end }}
{{- end }}