apiVersion: v1
kind: LimitRange
metadata:
  name: pminkows-cicd-limitrange
  namespace: pminkows-cicd
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      type: Pod