apiVersion: v1
kind: Namespace
metadata:
  name: pminkows-prod
  annotations:
    argocd.argoproj.io/sync: "true"
  labels:
    argocd.argoproj.io/managed-by: pminkows-cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: pminkows-stage
  annotations:
    argocd.argoproj.io/sync: "true"
  labels:
    argocd.argoproj.io/managed-by: pminkows-cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: pminkows-test
  annotations:
    argocd.argoproj.io/sync: "true"
  labels:
    argocd.argoproj.io/managed-by: pminkows-cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: pminkows-cicd
  annotations:
    argocd.argoproj.io/sync: "true"