kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-cicd
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: pminkows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: pminkows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-stage
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: pminkows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-test
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: pminkows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin