kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admins
users:
  - opentlc-mgr
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cicd-admins
users:
  - piomin
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: app-owners
users:
  - pminkows