apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/sample-dotnetcore-ex/prod
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/sample-dotnetcore-ex/stage
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows/sample-dotnetcore-ex/test
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/sample-kotlin-spring/prod
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/sample-kotlin-spring/stage
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows/sample-kotlin-spring/test
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD