apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: pminkows-cicd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: Deployment
    - group: '*'
      kind: Service
    - group: '*'
      kind: Route
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: Deployment
    - group: '*'
      kind: Service
    - group: '*'
      kind: Route
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sample-dotnetcore-ex-prod.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sample-dotnetcore-ex-stage.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sample-dotnetcore-ex-test.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sample-kotlin-spring-prod.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sample-kotlin-spring-stage.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sample-kotlin-spring-test.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-api-2-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-web-api-2-prod.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-api-2-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-web-api-2-stage.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-api-2-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-web-api-2-test.yaml