apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/prod/sample-dotnetcore-ex
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/stage/sample-dotnetcore-ex
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dotnetcore-ex-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows/test/sample-dotnetcore-ex
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-prod
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/prod/sample-kotlin-spring
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-stage
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/pminkows/stage/sample-kotlin-spring
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin-test
  namespace: pminkows-cicd
spec:
  destination:
    namespace: pminkows-test
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}
  source:
    path: apps/pminkows/test/sample-kotlin-spring
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD