apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dotnet-test
spec:
  params:
    - default: >-
        image-registry.openshift-image-registry.svc:5000/openshift/dotnet:5.0-ubi8
      description: Dotnet image
      name: DOTNET_IMAGE
      type: string
    - default: .
      description: >-
        The context directory within the repository for sources on which we want
        to execute dotnet goals.
      name: TEST_DIR
      type: string
  steps:
    - image: $(params.DOTNET_IMAGE)
      name: test-command
      resources: {}
      script: |
        #!/usr/bin/env bash
        dotnet test
      workingDir: $(workspaces.source.path)/$(params.TEST_DIR)
  workspaces:
    - name: source
