apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-dotnet-pipeline
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/piomin/s2i-dotnetcore-ex.git'
        - name: revision
          value: dotnet-5.0
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: s2i-dotnet
      params:
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: VERSION
          value: 5.0-ubi8
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/piotr-cicd/sample-dotnetcore-ex
      runAfter:
        - dotnet-test
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: dotnet-test
      params:
        - name: DOTNET_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/dotnet:5.0-ubi8
        - name: TEST_DIR
          value: app.tests
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: dotnet-test
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
