apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-registry-secret
  namespace: pminkows-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBVaqkP6QDrtOKspv3IbXtILNaG6cohM78tmXXiXFoHUO+94JBdIJsqnW9OLrDOxbg9NAtgI/q2oIuYHzJ+8ReSFzxVOx23vfXsJiup5swYQ17YP8xqVFOZLPQXgHK4S0Q5HEqIqXtoPXe7P70Si6IDAxSFLk5m2scEpiOGf/x/YYO8megH015z4oyciKLB1ubrN7Me/79SyTrGzimwoZQovnI/D/r5VlngQULMg8oYAuZCJPTDcF1TwtpVHxXdRXYgUBhXEjzLp81FhSWNzG4qEwvZMMSDu5egAsns1EZHLQeJL7hDkGgQdUUrX7P4IOIv/X503pn1CVnvkEzLbMshTKfSZp6xu1HtzXtfsjZJTbsjXvidMfyVD5oJigd7HBRvmPa2K/1EGutHPB1fSE8BJVGCfKmIGqV35whYrQYn4gcTzr4CW2xXQKfEsU+JmumvLafKt9OYALJYkKV9dL6r2oUKYqGP9Kzl69fH0eclqkIDEOx+gJhmE51a36I4PQR2vgYhK8LGnGr5slwWbAXUAe0yct3phbW6QuA6vNOmMEBBPJWuKYZED8SFoxwKg4qg94K9/d+fq1OPRcMmzOnhdx1qs/RHOcNYI57rAbXAxlUGkf9hxweuehX9oIFw5O0y38pyDawLa/KomF+gj62CUzqQNiv3RfubBYvVXrd/am1ZMBG95UkI4vV750Yao9xKm54UH13agtk8B/PasEJ7wPVOR+ebdfFMOKkPUmB/t7T5Df7q3OlzfQuQG34gWJxzIX79tw+g8+9gdmOcxQ9yBAFPUYcoADiBZtkg/+4m9Ht5hrAxaMRJX+VFgU1lm7kJVPusVGTojMh5RCrrIGw5lXbv+UVqbLn7Bb42hYi+fV4JHyLEH+b6ltSAZns2fHpVJULi3l/k2Gvz8LSpdHMKNWg29TZLq+gtlhcAn/GtyeJfHPCx/DLGD+X7
  template:
    metadata:
      name: quay-registry-secret
      namespace: pminkows-cicd
    type: kubernetes.io/dockerconfigjson
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-pipeline-service-account
  namespace: openshift-gitops
spec:
  patches:
    - id: patch1
      patchTemplate: |
        secrets:
          - name: quay-registry-secret
      patchType: application/strategic-merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          name: openshift-gitops
          kind: Namespace
        - apiVersion: v1
          name: openshift-gitops-argocd-application-controller
          namespace: openshift-gitops
          kind: ServiceAccount
      targetObjectRef:
        apiVersion: v1
        name: pipeline
        namespace: pminkows-cicd
        kind: ServiceAccount
  serviceAccountRef:
    name: openshift-gitops-argocd-application-controller
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-rolebinding
  namespace: pminkows-cicd
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: pminkows-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dotnet-pipeline-pvc
  namespace: pminkows-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-dotnet-pipeline
  namespace: pminkows-cicd
spec:
  params:
    - name: APP_VERSION
      description: Version number of application
      type: string
    - name: DOTNET_VERSION
      description: Version of .NET framework
      type: string
    - name: TESTS_DIR
      description: The name of the directory with unit tests
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/piomin/s2i-dotnetcore-ex.git'
        - name: revision
          value: dotnet-5.0
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: s2i-dotnet
      params:
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: VERSION
          value: $(params.DOTNET_VERSION)
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: >-
            quay.io/pminkows/sample-dotnetcore-ex:$(params.APP_VERSION)
      runAfter:
        - dotnet-test
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: dotnet-test
      params:
        - name: DOTNET_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/dotnet:$(params.DOTNET_VERSION)
        - name: TEST_DIR
          value: $(params.TESTS_DIR)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: dotnet-test
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
  namespace: pminkows-cicd
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

    </settings>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sonar-properties
  namespace: pminkows-cicd
data:
  sonar-project.properties: |
    sonar.organization=piomin
    sonar.login=f6b415dd54f74a7e3361976820544c2b138791d4
    sonar.qualitygate.wait=true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kotlin-pipeline-pvc
  namespace: pminkows-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-kotlin-pipeline
  namespace: pminkows-cicd
spec:
  finally:
    - name: s2i-java
      params:
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_ARGS_APPEND
          value: ''
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: IMAGE
          value: >-
            quay.io/pminkows/sample-kotlin-spring:$(tasks.get-version.results.version)
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: source-dir
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/piomin/sample-spring-kotlin-microservice.git'
        - name: revision
          value: s2i
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - test
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source-dir
        - name: maven-settings
          workspace: maven-settings
    - name: sonarqube
      params:
        - name: SONAR_HOST_URL
          value: 'https://sonarcloud.io'
        - name: SONAR_PROJECT_KEY
          value: sample-spring-kotlin
      runAfter:
        - maven
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source-dir
          workspace: source-dir
        - name: sonar-settings
          workspace: sonar-settings
    - name: get-version
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - sonarqube
      taskRef:
        kind: Task
        name: maven-get-project-version
      workspaces:
        - name: source
          workspace: source-dir
    - name: jira-issue
      params:
        - name: token-secret-name
          value: jira-token-secret
        - name: project-key
          value: PIOM
        - name: username
          value: piotr.minkowski@gmail.com
        - name: url
          value: piotrminkowski.atlassian.net
        - name: title
          value: $(tasks.get-version.results.version)
      runAfter:
        - get-version
      taskRef:
        kind: Task
        name: send-to-jira
  workspaces:
    - name: source-dir
    - name: maven-settings
    - name: sonar-settings
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dotnet-multiproj-pipeline-pvc
  namespace: pminkows-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-dotnet-multiproj-pipeline
  namespace: pminkows-cicd
spec:
  params:
    - name: APP_VERSION
      description: Version number of application
      type: string
    - name: DOTNET_VERSION
      description: Version of .NET framework
      type: string
    - name: TESTS_DIR
      description: The name of the directory with unit tests
      type: string
    - name: APP_PROJECT
      description: The file with project .csproj
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/piomin/web-api-2.git'
        - name: revision
          value: master
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: s2i-dotnet-multiproj
      params:
        - name: VERSION
          value: $(params.DOTNET_VERSION)
        - name: APP_PROJECT
          value: $(params.APP_PROJECT)
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: quay.io/pminkows/web-api-2:$(params.APP_VERSION)
      runAfter:
        - dotnet-test
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet-multiproj
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: dotnet-test
      params:
        - name: DOTNET_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/dotnet:$(params.DOTNET_VERSION)
        - name: TEST_DIR
          value: $(params.TESTS_DIR)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: dotnet-test
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jira-token-secret
  namespace: pminkows-cicd
spec:
  encryptedData:
    token: AgARTaoPqrknQpiBRfrGXT/JX9RaBpq2v/OslcZrGEOMbMCiL/TyGXL1FurqJiJXQrsqoZ1eQWorFFA2LUkaNTH4eGVmEgc3QfGBAIKGvzp1qOWD9j4n2YDQqIfA64UijFQtb2ELvugNaFwVNIt3bKjv9LQ/qIQzYRFTqf6czfZrihmZwVLGPEXGPXAN183h6/bgVYUJyXRWNfx78O5LC8Hc0OaFgMosXXwWQ/sRrgWqkJP99gHA+fpUp1brDJirlmtKSmdqlrqgNUKV/zOz16n22ln+C3WAEkv3AdulWcpiHcHnl4kATI84klsmkvcV5Qu3r8GeW3Mu4oRQKHIsZ8kMPm4u8azrQDdk4tUSxhIe/xE1vV4GhpHZC4n6/+YQrNpf1q7AIbgLZMYT5JKed2KvPCz6jSnhWotTO9xGu/MTGmDbSnCBKQL9yDJYyAAJgoWu9L4941yyBu25D5s1xCn96pqOZ82+R/GKKTa3DQnmHlxwh17fFX1W0ZJm8P+xFcBQQUEqlnqhy1zVnMVpzuGa2qIrO8R32xHVCtJO3spWdY7GYD/MwaUcIghQqnV/GIpvVSlXKlbBsdJ7FgcXP/V2iY8QrdCJzGl+gGTxBCNV9pWF3o6Bb8N78x1k8dxFX98KUYfUnMuhd5xQ+yz55S4Ns4QPf0x86j4FSrV1zhXr/hLK06lT2BBa6PZ/4EMruOQA4ZlDYqLAjjwJjUtFzBYFFUCoRR8gMQ0=
  template:
    metadata:
      name: jira-token-secret
      namespace: amq-demo
    type: Opaque