kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dotnet-pipeline-pvc
  namespace: pminkows-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azure-immediate
  volumeMode: Filesystem