apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-secret-token
  namespace: pminkows-cicd
spec:
  encryptedData:
    sonar.properties: AgALNHIm7Zb5nBMAWWxpE6lKcDo0aFHkcGAlsynozSxIK2mewjC5E7/Ad8YSoX1nuG3GfHPwsp+XPC37lIohsYbVU1q5LsjRmswlR8EjmfvShoO3vJLsa0Lp72zHmY7dnp+UFSknwwzE4QA2JV0vYyY535l+y9jqn0oDNBFMPVIX+ImkeJILe1zIUv3ZdTMsfTUdAQwV4mSZLtjQW8OWA5LXnozkdzyUlDsMMfR/FonFOkEnl+8j2lJexMkOEgLnLe8kncE2YR2cAwfgYtcV19Riupq59yJK/bRkCEtbHedjA/CWeDkUTLGoeD0Cs1gqV70k6YXoviFApQ+briBzoerSkgIXZnzys5VvfvnEpUt0mo8OcbfwVFxDHXSD2IMehCqvATnxQ5WBYie/MwhEcd0ckBahperFWi8DYfD38uAV0zFHSJwnn/FmJ4C8dOaUryKATNHLDiqP6I+PVjdrLNv6AABEVA37ZrOloJUKPsY85hsYzhVfCiPIklCdiuSAc7mTlOPo3oIbeaEXH7eMEUi7tswphi7vmAuhX3GTK/4Mc1nLF4tPgS4MPhlxmRV3BcXZpOOc5sUhEzht6YD3LQ/J5w2lBcKHX5fqtoT+J8zkldBzsF0ipwTlvqBrxQmQASLkuCQOs9iJ9txFwLVRAxS1NzH6c2zBLQSYiv2zYfKpYz4Cbi6gTwEykTg/0WkVNWq0Rt6FNCQO1q3TQJD25I6/F03QRwpY4wJCMhf9fMMGL+SnfJ0uWD8SmKd1D+onln1/Yux5Ygj8Zs0pf97n0dXYnnmSh/zCk4KLQQCbLxZ9y2KemyJ1s0ZG20qpDoy6OTJRyH9prrlHjw7LzA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-secret-token
      namespace: pminkows-cicd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-registry-secret
  namespace: pminkows-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBJYSyiexv+fFQq1MFebiveKf7I2QAG4ImpRXBN6Xt6wNxzyleQZr0q55QGHikSUX26viipD32kliHnC1uiQlJWrRYXMtPlxEh7Ll75rWoz7UW+StlHgJi4j5tK0Eu17wz1WM/n9/OhCB7rWm9Xv9YmxRgQ1qivC1udWfoE7Juyn6fsxZCpPX7KgKMPUzifDmgbqAUfrQguqBZJ9izkQwv9wV1756asElSoB7qQBmLwONhxsKpRrm4/peoi7w4zggTNs9Mekd7tvdoo+ku99O7V5Vz79wMRgDd8dAFQhq/xXW5FfYqLgMODVtg4Z7T6Wh9EE/Ia26F+RXoOoNGB4hLXq3UrtoTT/9KNxpwLtWdelgqv2z4VHg+8V+0/Ffpl/UmdK/PQWa4SenfP03GrSCFCpMKG9fu8FiFzmgysPpgnynczojy+GFbo8aO7GDURmXSlM6Jd7jE1knpwiYvLGGR+WSmNuLncJ0BisnUV66MLuN9EI8VtCzOqiP4/uxRnPXfxMj8LOmxpRy6UhSCeoFfCZA/md4ehqXJkbT8qyJSZP4NIGDkCSxaN77FvGEc66+0arFH0+QgKafeZ/7RdKlBJjQ/j0y69tONvZiCcDyIkw6yr+uDIucpSoT7iPWF0AojD+PAnaEhPb1Qw92oYw5dzf5Fde6VJlMDuVXqzEZeGgxILL+6kFFmn3vEDrSijn5Wwv4BL+RTtfpKk6+iLrBWI79ViR3GMviI41G1ZtE0CECvoM9FHh+mITQZoWlQCM2/SFM83i5f6z4F0LMxV0PIFpfhgmI1CPUiekvdFpPumjl6GuFSoUScImb7ToEkFWs9EgsBS3Hj6UbZFbuO3fSIdiVREHZkub/PSzFTMw6pJREvy7qCOc6zAN7qCkiKlhozr5WSGnUEkGosvS0b1ebo6DO68Xc81XR/gi7nlFPwtoGD0ePZ7GtkyNSjP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: quay-registry-secret
      namespace: pminkows-cicd
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jira-token-secret
  namespace: pminkows-cicd
spec:
  encryptedData:
    token: AgCnWHIYhYkQ70BIIUtBy+Bq7ONbwLiqeZZZQ6I7Vs4jdlq0w7RwWwjC2kbD3iDhzyP05ord+0WwSrGwu7lSfqHtaG+NcwLfZ9vBSJucxsZKNdjyVJhRIzFUwBFW5VUWihe1Fdi1oUlBDOjFgZuwQ/ZwNro2FAMhl/zQGP1bPHrzdRwL7Aw+FsYai+0E+OG+ztX3hj25ZT4Lcpos6jPieBBWJOW1p2zxJZLXSdKMKguOjerVz+UWZk0ynElTwFoCjGqG5O1Ctwy/MGa00atQ6vmHum5yXwd00DNbYJOnQPNDBF9QIgVS8YClstXK1KSEyvc5ilk3u/cebWTZipZbikRHUlW/H458+T9nF50IFaxAh/eG4XMbU7O8hnluI/YjWUVEA54QlP6/zOITwwIQuHIgVgt8nqPa+cHwhcQrSRetUdWqC6yyCvl0e9wOm4BpwxfnWsdDqUBBHNi5o4V4BdsICWMuGrHFulhUdSfq13WRQAG33LOyX7cVTiVBMfpaeCbBdRmhZ/06T9mHlU+ngUlTZzCEJegHQBawwh2r/vt12NpL2NS9m5qST72ik1w0qElTzkMHJxbzpovmzV0bw5QlZ3hAavvzHQg9s6UaS3IGcYM3ObW5KZfQ1LdwOOBr88J/ckN+ZQmmIXGDufUBgBz6e+JsCqkhLDbuhPK8N+Rm4HIlXpumgDoyhqjXpQm4A6JoAWdkin35B40ct7FN36MS2GJTVRXvxpY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: jira-token-secret
      namespace: pminkows-cicd
    type: Opaque