apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-kotlin-spring-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-kotlin-spring
  template:
    metadata:
      labels:
        app: sample-kotlin-spring
    spec:
      containers:
      - name: sample-kotlin-spring
        image: image-registry.openshift-image-registry.svc:5000/pminkows-cicd/sample-kotlin-spring:1.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
