apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.clusterName }}-worker
  namespace: {{ .Values.clusterName }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.clusterName }}
  name: worker
  platform:
    {{- if eq .Values.provider "Amazon" }}
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: {{ .Values.workerType }}
    {{- end }}
    {{- if eq .Values.provider "Google" }}
    gcp:
      type: {{ .Values.workerType }}
    {{- end }}
  replicas: {{ .Values.workerReplicas }}