apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-pull-secret
  namespace: {{ .Values.clusterName }}
stringData:
  .dockerconfigjson: # injected on create
type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
spec:
  encryptedData:
    install-config.yaml: AgDBuL/woVO0d5C1hRUWuHN3bSGNEl1qsKmEc1ruM5HQWDNCqaj/EuRanTKL+lDNIinQIn4jbcGKulPWNk8arpck9pkShhPudrGhM5+af6LzwgCcRhbwbmC8/1vd4nG0dA2yF5qfk69CkTxfq26Htpg0VRG/ZuQol86lyDUPoBuMv9T6MXHXg+XXPkgWVXGGyGEejWyLB9ffRdzbWn0BLF+z8FMZ4kegSpZMTaIbBsmoYDWExNfugHE+cenGv9E7QrU88Xr/1jkg5T2Jm2tDCGnZsBCCpScczL8WmyTJIMf85OA0tXjOoOvjuB0er3sqxY3BYSV/y8YXaM4yJHUZdSIyGsOT/rmIUcvvDWCXSSc2Lwm1h9p/oNevwgQUedF38D39Aqx4qGaE8aJDCzsWoJ7QarWTN47j6PYNj8SKLC+Omiqz42tnHB/UpcjlNz8660nRpcOARO9tdLpR4hWFBFDOa8tIjc5OsCm23/iNsk/KK89UUlbFYNCIUcEXHpuct1fUHws/v05I8Yv+LQ2EJ1xeL47XaHTQwbi828PAd/1rR14WZx+tm6IWBRddDBQ1fzDiYqMtHJ05e0J/Ot3v90DP1YZvETYCUHyINVIxnh1mvHlnuiLCpHJ734FCO8EgGNijUdM1I44r3o7ir9NaW/xxCD7DnP+NpmK+XLAss4l8Y2+ahNR9lXWq5/80ZV8/hnQc0WqFyOaVqBtv3oyFtFwmJKi5MchcXT3B3Xi2YZqN4xhcwf9UPaDPoDaW+YrTadG6wQyLboaunHJh+ZetHfrMFNaqyRBop9JyF5nuaFL4AThQEXFlktovYZX/MF1eavjAcbYQAwIc4RhgwqqUdcrS/WO99Ru5CjLRDuGDLWwnn8aVQvM/04TvBC+RZoH6TFMtTt74tb6cs+OBcftBUsswnIaiT/9o6G0QJd4GyKIXybcTZUsktZW2I73l8BLUogD8vx8uF/sVA7z06heAuYshlXKVcw1exD8Y4v2/k5IsKrJ4tCg5VO0zLzAwHu0meFtfd9XhP9M+MTSj8WeKvLnXv46836s1v0aL8n0sPDNg5+RbBwVP2kTikNzMowSkJfGpnKgeW07oojwowzfG3PoqLaR8xnOwOa84jh9QhXq5wB+inUdZCqEuIxPwCohIpGf+xN4kARGj69rRoBeQXOO2lttLOxRVBX1Mn7Wu5QusBnKUpe0iKmxgXi8qwKKe9ItSNn9qucn7WJwYEbNha4y+QyqIc953J2qcr9PTNwoYKULI3cAJRR9asvqRTpwnilQX3tpRnaDrdMU0+nI/pNC77S1ghYfsLbp2MisW/CfONY2g9B4Tn5Eg3mNcAK2ibX55GOa2Ck5uOCcWi0BBbV8WEndFvNrMOMB3P/Pd0DxIJNMeGTnehRZwinpJwexDw7zDgHx6BtOyEOY+GlPg03iBg8RfCJVeDgnH5sY8eni6uckcpzqVduOZFNDJ/izcLtkgUr6GZt1F+U5FQguC/YYtHmkwQP6CDpoWqlj68MbOoiAUlV7okJsNvtSBOGDyzeOOAZfoIDK1O97wR5GpI412G/N+WDr/72WGedV6juBb0eFaYshdHtjGAPgAHYKNpeYYqG5pnO6ICr/tNA0Uf7kHSimjXzuJ9nOzK/7BheMn0SH4815eb96TX6bqtbYpLscc56CHCj0iPNOcMA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ .Values.clusterName }}-install-config
      namespace: {{ .Values.clusterName }}
    type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-ssh-private-key
  namespace: {{ .Values.clusterName }}
stringData:
  ssh-privatekey: # injected on create
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.clusterName }}-gcp-creds
  namespace: {{ .Values.clusterName }}
stringData:
  osServiceAccount.json: # injected on create